# Generated by Django 4.2.2 on 2023-06-15 11:25

import calbuddy_api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calbuddy_api", "0003_alter_meal_date_delete_day"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", calbuddy_api.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff status"),
        ),
    ]
