# Generated by Django 4.2.2 on 2023-06-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calbuddy_api", "0005_meal_calorie_limit_exceeded_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="date"),
        ),
    ]
