# Generated by Django 4.2.2 on 2023-06-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calbuddy_api", "0006_alter_meal_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="calorie_limit_exceeded",
        ),
        migrations.AddField(
            model_name="meal",
            name="within_calorie_limit",
            field=models.BooleanField(
                default=True, verbose_name="within calorie limit"
            ),
        ),
    ]
